name: Packages Testing

on: 
  workflow_dispatch:
  
  pull_request:
    branches:    
      - 'main'

jobs:
  Testing:
    uses: 34ML/Actions-Config/.github/workflows/Laravel-Packages-Testing.yml@master
    with:
      docker-image: ghcr.io/34ml/docker-laravel:php-8.2-composer-2.0-node-19.9.0
    secrets: inherit # pass all secrets
